# **NumPy (Numerical Python)**

## 1. Introducción

¿Qué es Numpy y por qué es importante para el análisis de datos?

+ NumPy (Numerical Python) es una biblioteca de Python diseñada para trabajar con arreglos multidimensionales (arrays) de manera eficiente.
+ Es la base para muchas otras bibliotecas científicas como pandas, SciPy y scikit-learn.

Ventajas:

    + Sintaxis concisa y poderosa para operaciones con arrays.
    + Operaciones rápidas y optimizadas (usa código compilado en C) más eficientes que las operaciones con listas de Python.
    + Soporte para operaciones matemáticas, de algebra lineal, estadísticas, generación de números aleatorios y muchas más.
    + Manipulación sencilla de grandes volúmenes de datos.
    + Menor consumo de memoria.

Conceptos Clave:

    + ndarray: Estructura de datos principal (homogénea, multidimensional).
    + homogénea: Los arreglos numpy sólo puede almacenar datos del mismo tipo.
    + Vectorización: Operaciones aplicadas a todo el arreglo sin bucles.
    + Broadcasting: Reglas para operar arreglos de diferentes tamaños.

El sitio web de NumPy es https://numpy.org/

## 2. Configuración Inicial

Para empezar a utilizar Numpy primero se debe instalar. Para esto en VSCode abra un cmd y digite:
~~~
pip install numpy
~~~

Luego, ejecute la siguiente celda:

In [1]:
# Importar la librería
import numpy as np

np.__version__

ModuleNotFoundError: No module named 'numpy'

## 3. Creando Arrays de Numpy

Hay diferentes formas de crear arrays:

    A partir de listas o tuplas (np.array()).
    Arrays de ceros (np.zeros()).
    Arrays de unos (np.ones()).
    Arrays con valores secuenciales (np.arange(), np.linspace()).
    Arrays con valores aleatorios (np.random.rand(), np.random.randint(), np.random.randn()).

Algunos de los atributos importantes de los arrays son:

    .ndim: número de dimensiones.
    .shape: forma del array (tupla con el tamaño de cada dimensión).
    .size: número total de elementos.
    .dtype: tipo de datos de los elementos.

In [2]:
import numpy as np

# Ejemplo de lista de Python
lista_python = [1, 2, 3, 4, 5]
print(f"Lista de Python: {lista_python}, tipo: {type(lista_python)}")

# Creación de un array de NumPy a partir de una lista
array_numpy = np.array(lista_python)
print(f"Array de NumPy: {array_numpy}, tipo: {type(array_numpy)}")

Lista de Python: [1, 2, 3, 4, 5], tipo: <class 'list'>
Array de NumPy: [1 2 3 4 5], tipo: <class 'numpy.ndarray'>


In [14]:
array_2 = np.array([1,4,5,6])
print(array_2)
print(type(array_2))
print(array_2.shape)

[1 4 5 6]
<class 'numpy.ndarray'>
(4,)


In [5]:
# Creación de diferentes tipos de arrays
zeros_array = np.zeros((2, 3))
print(f"Array de ceros:\n{zeros_array}, \ndimensiones: {zeros_array.ndim}, forma: {zeros_array.shape}, tipo de datos: {zeros_array.dtype}")


Array de ceros:
[[0. 0. 0.]
 [0. 0. 0.]], 
dimensiones: 2, forma: (2, 3), tipo de datos: float64


In [7]:
ones_array = np.ones(5, dtype=int)
print(f"Array de unos:\n{ones_array}, \ntipo de datos: {ones_array.dtype}")

Array de unos:
[1 1 1 1 1], 
tipo de datos: int64


In [8]:
arange_array = np.arange(0, 10, 2)
print(f"Array con arange: {arange_array}")

Array con arange: [0 2 4 6 8]


In [9]:
linspace_array = np.linspace(0, 1, 5)
print(f"Array con linspace: {linspace_array}")

Array con linspace: [0.   0.25 0.5  0.75 1.  ]


In [17]:
random_array = np.random.rand(2,2)
print(f"Array aleatorio:\n{random_array}")

Array aleatorio:
[[0.95616296 0.66881503]
 [0.1640473  0.2165277 ]]


In [12]:
random_array = np.random.randint(1, 10,(2,2))
print(f"Array aleatorio:\n{random_array}")

Array aleatorio:
[[7 9]
 [5 3]]


### Indexado y Slicing

In [71]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

In [72]:
print(a.shape)

(3,)


In [73]:
print(a[1])

2


In [74]:
print(a[0:2])

[1 2]


In [75]:
print(b.shape)

(2, 2)


In [76]:
print(b[0, 1])     # 2

2


In [77]:
print(b[:, 1])

[2 4]


## Ventajas con respecto a las istas de Python

In [18]:
# Tenemos la siguientes listas de Python:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

PREGUNTA:
¿Cuál será el resultado de a + b?

In [19]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

PREGUNTA: ¿Cuál será el resultado de a * 3?

In [20]:
a * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

#### Una solución es implementar las operaciones usando bucles. Se pueden usar los comandos While o For. También se puede hacer uso de List Comprehension (https://realpython.com/list-comprehension-python/)

In [ ]:
# Bucle for accediendo a los elementos usando índices
c = []
for i in range(len(a)):
    c.append(a[i]*3)

print(c)

In [ ]:
# Bucle for accediendo a los elementos directamente
c = []
for i in a:
    c.append(i*3)

print(c)

In [ ]:
# List Comprehension
c = [x*3 for x in a ]

print(c)

### Ejercicio
Implemente un programa que sume dos arreglos elemento a elemento.

In [21]:
a = [1, 2, 3, 4, 16, 17]
b = [5, 6, 7, 8, 9, 10]
c = []

In [22]:
for i in range(len(a)):
    c.append(a[i]+b[i])

print(c)

[6, 8, 10, 12, 25, 27]


In [24]:
d = [a[i] + b [i] for i in range(len(a))]
print(d)

[6, 8, 10, 12, 25, 27]


### Creamos un numpy array

In [25]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
array_a = np.array(a)
array_b = np.array(b)

PREGUNTA:
¿Cuál será el resultado de array_a + array_b?

In [27]:
c = array_a + array_b
print(c)
print(type(c))

[ 6  8 10 12]
<class 'numpy.ndarray'>


PREGUNTA:
¿Cuál será el resultado de array_a * 3?

In [28]:
d = array_a * 3
print(d)
print(type(d))

[ 3  6  9 12]
<class 'numpy.ndarray'>


## Copias superficial y copia profunda

In [29]:
a = np.array([1,2,3,4])
b = a
a[0] = 10
print(type(a))
print(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[10  2  3  4]
<class 'numpy.ndarray'>
[10  2  3  4]


In [30]:
a = np.array([1,2,3,4])
b = a.copy()
a[0] = 10
print(type(a))
print(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[10  2  3  4]
<class 'numpy.ndarray'>
[1 2 3 4]


## Poder Computacional

In [31]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print(type(my_arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [32]:
print(len(my_list))
print(my_arr.shape)

1000000
(1000000,)


#### Ejercicio
+ Ejecute el siguiente código.
+ ¿Qué hace?
+ ¿Qué puede concluir?

In [50]:
import time

# Registrar el tiempo inicial
inicio = time.time()

# Bloque de código a medir
a = [x * 2 for x in my_list]

# Registrar el tiempo final
fin = time.time()

# Calcular el tiempo de ejecución
tiempo_ejecucion = fin - inicio
print(f"Tiempo de ejecución: {tiempo_ejecucion:.4f} segundos")

Tiempo de ejecución: 0.0570 segundos


In [54]:
import time

# Registrar el tiempo inicial
inicio = time.time()

# Bloque de código a medir
b = my_arr * 2

# Registrar el tiempo final
fin = time.time()

# Calcular el tiempo de ejecución
tiempo_ejecucion = fin - inicio
print(f"Tiempo de ejecución: {tiempo_ejecucion:.4f} segundos")

Tiempo de ejecución: 0.0030 segundos


In [60]:
import time

# Registrar el tiempo inicial
inicio = time.time()

# Bloque de código a medir
a = [x ** 2 for x in my_list]

# Registrar el tiempo final
fin = time.time()

# Calcular el tiempo de ejecución
tiempo_ejecucion = fin - inicio
print(f"Tiempo de ejecución: {tiempo_ejecucion:.4f} segundos")

Tiempo de ejecución: 0.0732 segundos


In [65]:
import time

# Registrar el tiempo inicial
inicio = time.time()

# Bloque de código a medir
b = my_arr ** 2

# Registrar el tiempo final
fin = time.time()

# Calcular el tiempo de ejecución
tiempo_ejecucion = fin - inicio
print(f"Tiempo de ejecución: {tiempo_ejecucion:.4f} segundos")

Tiempo de ejecución: 0.0030 segundos


In [69]:
import timeit

# Definir una función para el bloque de código
def mi_funcion():
    a = [x ** 2 for x in my_list]

# Medir el tiempo
tiempo = timeit.timeit(mi_funcion, number=100)
print(f"Tiempo promedio de ejecución: {tiempo/100:.4f} segundos")

Tiempo promedio de ejecución: 0.0780 segundos


In [70]:
import timeit

# Definir una función para el bloque de código
def mi_funcion_2():
    b = my_arr ** 2

# Medir el tiempo
tiempo = timeit.timeit(mi_funcion_2, number=100)
print(f"Tiempo promedio de ejecución: {tiempo/100:.4f} segundos")

Tiempo promedio de ejecución: 0.0029 segundos


## Arrays Homogéneos

#### Ejercicio
+ Ejecute el siguiente código y escriba un comentario de acuerdo con los resultados obtenidos.

In [66]:
data1 = [6, 7., 8, 0, 1]
arr1 = np.array(data1)
print(1)
print(type(arr1))
#
print(2)
print(arr1.dtype)
print(arr1)
#
arr1 = np.array(["1", 3.5, 5])
print(3)
print(arr1.dtype)
print(arr1)
#

1
<class 'numpy.ndarray'>
2
float64
[6. 7. 8. 0. 1.]
3
<U32
['1' '3.5' '5']


### Cambiar el tipo de dato en un arreglo numpy

In [ ]:
arr1 = np.array([5,8, 5])
print(arr1.dtype)
print(arr1.nbytes)
print(arr1)

In [ ]:
arr1 = np.array([5,8, 5],dtype='int16')
print(arr1.dtype)
print(arr1.nbytes)
print(arr1)

In [ ]:
arr1 = np.array([5.1,8, 5])
print(arr1.dtype)
print(arr1.nbytes)
print(arr1)

In [ ]:
arr1 = np.array([5.1,8, 5],dtype='int16')
print(arr1.dtype)
print(arr1.nbytes)
print(arr1)

In [ ]:
arr1 = np.array([5,8, 5],dtype='float32')
print(arr1.dtype)
print(arr1.nbytes)
print(arr1)

In [ ]:
a = np.array([.22, .270, .357, .44, .50], dtype=np.float64)
print(a.dtype)
print(a)
b = a.astype(np.int32)
print(b)

In [ ]:
a = np.array([.22, .270, .357, .44, .50], dtype='str')
print(a)
b = a.astype(np.float64)
print(b)

## Tamaño de un arreglo numpy

In [ ]:
a = np.arange(100)
print(type(a))
print(a)

In [ ]:
print(a.shape)
print(type(a[0]))
print(a[2])

In [ ]:
a[3]

In [ ]:
a = a.reshape(-1,1)
print(a.shape)
print(a)

In [ ]:
print(type(a[0]))
print(a[0])

In [ ]:
print(type(a[6,0]))
print(a[6,0])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c.shape)
print(c)

In [ ]:
rows, cols = c.shape
print(rows)
print(cols)

In [ ]:
row2 = c.shape[0]
col2 = c.shape[1]
print(row2)
print(col2)

## Generación de arreglos

In [ ]:
# Creando un array de zeros con cinco elementos
np.zeros(5)

In [ ]:
# un objeto ndarray de 5x5
a = np.zeros((5,5))
print(a)
print(a.shape)

In [ ]:
b = np.ones((3,3))
print(b)
print(b.shape)

In [ ]:
print(b[0,0].dtype)

In [ ]:
# creando un array de 0 hasta 99
print(np.arange(100))
# creando un array de 10 hasta 79
print(np.arange(10,80,5))

In [ ]:
# creando un array númerico de 10 hasta 1000 con saltos de 10
a= np.arange(10, 1000, 10)
print(a)
print(len(a))

### Ejercicio
+ Ejecute el siguiente código y determine qué hace la función `np.linspace()`

In [ ]:
a = np.linspace(0, 100, 5)
print(a)
print(len(a))

In [ ]:
a = np.linspace(0, 100, 10, endpoint=True, dtype=np.int64)
print(a)
print(len(a))

In [ ]:
a = np.linspace(0, 100, 10, endpoint=True, dtype=np.int64)
print(a)
print(len(a))

In [ ]:
a = np.linspace(0, 100, 20, endpoint=True, dtype=np.float64)
print(a)
print(len(a))

In [ ]:
a = np.linspace(0, 100, 20, endpoint=True, dtype=np.float64)
print(np.array_str(a, precision=2))
print(len(a))

In [ ]:
# creemos un array de 1x1000 utilizando randn
data = np.random.randn(1000)
print(len(data))

In [ ]:
# slicing
print(data[:10])

## Funciones para operar matrices (álgebra lineal)

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a.ndim)
print(a.shape)
print(a)

In [ ]:
b = a.copy()
b = b.reshape(5,2)
print(b.ndim)
print(b.shape)
print(b)

#### Ejercicio
+ Ejecute el siguiente código e indique qué hace.

In [ ]:
c = b.T
print(c.shape)
print(c)

### Ejercicio 1
+ Usando numpy encuentre la solución para el siguiente sistema de ecuaciones:
    ~~~
    x0 + 2 * x1 = 1
    3 * x0 + 5 * x1 = 2
    ~~~
+ Recuerde para un sistema matricial Ax = B, la soluciómn se encuentra como: x = (A^-1)*B

### Ejercicio 2: Indexación Básica

a) Crea un arreglo 2D de 3x3 con números aleatorios del 1 al 9.

b) Imprima la segunda fila y la primera columna.

c) Cambia el valor de la posición (2, 2) por 15 e imprima el arreglo modificado.

### Ejercicio 3: Operaciones con Matrices

a) Cree dos arreglos 2D de 5x5: con valores aleatorios entre 20 y 40.

b) Realiza las siguientes operaciones: suma de los arreglos, multiplicación elemento a elemento y multiplicación matricial (producto punto).

c) Imprime los resultados de cada operación.

### Ejercicio 4: Filtrado de Datos

a) Cree un arreglo con 100 números aleatorios entre 0 y 100.

b) Cree otro arreglo con los valores mayores a 50.

c) Calcula el promedio, la media y la desviación estándar de este nuevo arreglo.

c) Imprime el arreglo original, el arreglo filtrado, el promedio, la media y la desviación estándar.